/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */
import type {
  MemberChatsDTO
} from '.././model'
import { customInstance } from '.././custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  /**
 * Gets all chats of a member
 */
export const getAllChatsByMember = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<MemberChatsDTO[]>(
      {url: `/api/v1/member/${id}/chats`, method: 'GET'
    },
      options);
    }
  export type GetAllChatsByMemberResult = NonNullable<Awaited<ReturnType<typeof getAllChatsByMember>>>
