/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */

export interface ChatMessageDTO {
  content?: string;
  message_id?: string;
  sender_id?: string;
  sent_at?: string;
}
