/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */
import type { CreateChatDTOType } from './createChatDTOType';

export interface CreateChatDTO {
  creator_id?: string;
  description?: string;
  name?: string;
  type?: CreateChatDTOType;
}
