/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */

export interface FileSearchDTO {
  chat_id?: string;
  detailed?: boolean;
  message_id?: string;
}
