/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */

export interface FileURLDTO {
  message_id?: string;
  original_name?: string;
  sender_id?: string;
  sent_at?: string;
  url?: string;
}
