/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */
import type { FileUploadResultDTOUploadResult } from './fileUploadResultDTOUploadResult';

export interface FileUploadResultDTO {
  file_id?: string;
  upload_result?: FileUploadResultDTOUploadResult;
  url?: string;
}
