/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */

export type FileUploadResultDTOUploadResult =
  (typeof FileUploadResultDTOUploadResult)[keyof typeof FileUploadResultDTOUploadResult];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileUploadResultDTOUploadResult = {
  SUCCESS: 'SUCCESS',
  FAIL: 'FAIL',
} as const;
