/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */

export type GetTokenType = typeof GetTokenType[keyof typeof GetTokenType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTokenType = {
  CONNECTION: 'CONNECTION',
  SUBSCRIPTION: 'SUBSCRIPTION',
} as const;
