/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */

export type MemberChatsDTOChatType =
  (typeof MemberChatsDTOChatType)[keyof typeof MemberChatsDTOChatType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberChatsDTOChatType = {
  DIRECT: 'DIRECT',
  GROUP: 'GROUP',
  CHANNEL: 'CHANNEL',
} as const;
