/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */
import type { MemberChatsDTOChatType } from './memberChatsDTOChatType';

export interface MemberChatsDTO {
  chat_id?: string;
  chat_name?: string;
  chat_type?: MemberChatsDTOChatType;
  member_nickname?: string;
  message_id?: string;
  sent_at?: string;
  text_preview?: string;
}
