/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */

export interface MessageFiltersDTO {
  chat_id?: string;
  limit?: number;
  message?: string;
  offset?: number;
  saved?: boolean;
}
