/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */

export interface OnSendMessageDTO {
  author_id?: string;
  chat_id?: string;
  content?: string;
}
