/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */
import type { FileUploadResultDTO } from './fileUploadResultDTO';

export interface UploadedFilesDTO {
  uploaded_files?: FileUploadResultDTO[];
}
