/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Webchat REST API
 * Webchat application
 * OpenAPI spec version: 3.0
 */
import type {
  FunctionDTO,
  GetTokenParams
} from '.././model'
import { customInstance } from '.././custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  /**
 * Gets a token of specified type for centrifugo
 */
export const getToken = (
    params: GetTokenParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<string>(
      {url: `/api/v1/token`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Gets all the available functions to assign to a custom role
 */
export const getAllFunctions = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<FunctionDTO[]>(
      {url: `/api/v1/functions`, method: 'GET'
    },
      options);
    }
  export type GetTokenResult = NonNullable<Awaited<ReturnType<typeof getToken>>>
export type GetAllFunctionsResult = NonNullable<Awaited<ReturnType<typeof getAllFunctions>>>
