import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import { WSMessagesProcess } from '@/shared/processes/ws';
import AuthProvider from '@/shared/providers/auth';
import WSProvider from '@/shared/providers/ws';

import './globals.css';

const font = Nunito({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <AuthProvider>
          <WSProvider>
            <WSMessagesProcess>{children}</WSMessagesProcess>
          </WSProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
